scene.setBackgroundColor(1)
let mySprite = sprites.create(assets.image`Icon`, SpriteKind.Player)
mySprite.setPosition(80, 80)
mySprite.setScale(4, ScaleAnchor.Middle)
let textSprite = textsprite.create("Hello George!", 0, 9)
textSprite.setOutline(1, 6)
textSprite.setMaxFontHeight(14)
textSprite.setPosition(85, 25)
textSprite.setScale(1, ScaleAnchor.Middle)
